import React from 'react';
import { Link } from 'react-router-dom';

const Theproblem = () => {
  return (
    <div>
      {/* <div className="panel panel-default"> */}
      <div className="panel-body">
        <h3 className="panel">
          {/* What can we learn from other allied health professions? */}
        </h3>
        <div className="wrapper">
          <p>
            As of 2017, the O&P community is composed of approximately 6,000
            professionals. Of those 6,000 practitioners, females make up just
            27%. The male to female ratio has historically favored males
            however; the patient gender distribution is relatively evenly
            distributed. That said, why is the field so unbalanced?
          </p>
          <br />
          <div style={{ display: 'flex', justifyContent: 'center' }}>
            <div>
              <img
                src="/css/img/genderop.png"
                alt="FEMALE TO MALE distribution"
                width="500"
              />
            </div>
          </div>
          <br />
          <p>
            In an attempt to answer these questions, I have done a literature
            review as outlined by (Webster and Watson, 2017) utilizing Google
            Scholar as well as the University of Texas Libraries. My goal was to
            try to find out what the O&P community has recorded as reasons for
            this imbalance. I wanted to find articles on leadership,
            multigenerational values and suggestions of how leadership can
            address the issues of this particular time in history. I was sure
            I'd find data generated by the O&P community now that it is required
            that we earn a Master's Degree in order to enter the field.
          </p>
          <p>
            I found that a literature search in Google Scholar may return
            1,000’s of results when searching “leadership in nursing or physical
            therapy” however, only 1-2 relevant articles pertaining specifically
            to O&P. I found a lack of peer reviewed research on the field of O&P
            relating to our organizational behavior, organizational culture and
            a lack of guidelines pertaining to our peer leadership/mentoring. I
            then turned to the nursing community and found copious research on
            these subjects. As it is today, current managerial leadership in
            Orthotics and Prosthetics is taught by “do as I say and sometimes do
            what I do”. This method of mentoring may not be appropriate for
            those newly entering the field.
          </p>
          <p>
            Zero articles pertaining to O&P.... If we are to maintain
            professionalism and improve our patient care practices, we are
            obligated to move outside the NUPOC definition of "research" and
            expand our sights to include how individuals in our organizations
            behave.
          </p>
          <br />
          <p>
            <h4>Generational Gap in Experience</h4>
          </p>
          <p>
            In order to be sustainable in the future, we must change how we look
            at research and ask ourselves how we can best serve our public by
            recognizing changing trends in communication and perspectives toward
            health care. These shifts have been documented extensively by other
            professions and show that the millennial generation looks at
            problems through a different lens than we have in the past. O&P
            should embrace a shift toward examining not only our biomechanical
            applications but also to look at how we communicate with those that
            are new to the workforce.
          </p>

          {/* <p>
            To be recognized as a profession, something the organization has
            struggled with, we should develop a culture that includes
            transformational leadership. Most of the literature to date reflects
            concern for managing patient centered needs and concerns, patient
            compliance and O&P technology. There is no peer reviewed research
            into transformational leadership within O&P. This may be an
            increasing concern as we compete for pay sources, attempt to
            maintain a level of professionalism equal to that of other allied
            health care groups and may be impacting our recruitment and
            retention.
          </p>

          <p>
            The dynamics of our organization has changed in recent decades. We
            are having more difficulty filling seats in our O&P education
            programs as evidenced by the reduction of “wait lists” that were
            prevalent in the 1990’s. This shift may be due to an increase in
            schools but may equally be likely due to the increased educational
            requirements. Even more, this shift may be due to a lack of interest
            in the field. The “Practice Analysis of Certified Practitioners in
            the Disciplines of Orthotics and Prosthetics” is a report that is
            released every 5 to 7 years but is not widely accessible. One must
            know of its existence to obtain the information within.{' '}
          </p> */}

          <p>
            It is noted in the most recent edition of “Practice Analysis of
            Certified Practitioners in the Disciplines of Orthotics and
            Prosthetics”, a report that is released every 5 to 7 years, that
            most practitioners have been in the field for more than 11 years
            with a stark decrease in the number of clinicians serving 10 years
            or less. I’m not sure what this indicates but would lead me to
            wonder if there is a lack of interest in the field or if individuals
            leave the field.
          </p>
          <br />
          <div style={{ display: 'flex', justifyContent: 'center' }}>
            <div>
              <img
                src="/css/img/experience2015.png"
                alt="some text"
                width="500"
              />
            </div>
          </div>
          {/* <br /> */}
          <p>
            This is a question that could be answered with a look into our
            culture. As we move toward requiring a Master’s and PhD level of
            education our focus has shifted from encouraging new practitioners
            to join the field to maintaining and educating those that are
            already established.{' '}
          </p>
          <br />
          <p>
            With the O&P workforce of just over 6,000 practitioners in 2017, we
            continue to be a small division of medicine. Recruiting should be a
            focus to sustain, and retention to grow the field, as qualified O&P
            practitioners will be needed to care for our population. We should
            focus on balancing the gender equality as well as the ethnic
            demographic descrepancy. and ethnicity within O&P in the United
            States. Of the respondents, 84% of the field is White/Caucasian with
            a startling .
          </p>

          <p>
            However, the age distribution, as indicated by Figure 1, shows that
            the workforce is evenly distributed between the ages of 25-64 years
            (Whiteside, S, et. al, 2015). Because the relatively even
            distribution of the current O&P workforce across age groups, we are
            provided an environment to share our perspectives relating to
            generational differences and begin to explore why our gender and
            ethnic distribution are not as equally distributed. With this
            information, we have an opportunity for a shift toward
            transformational leadership implementation and an increased
            awareness of our gender, ethnic, and generational diversity.{' '}
          </p>
          <br />
          <div style={{ display: 'flex', justifyContent: 'center' }}>
            <div>
              <img src="/css/img/genmakeup.png" alt="some text" width="500" />
            </div>
          </div>
          <br />
          <p>
            <p>
              {' '}
              To grow the field and encourage new applicants to our O&P schools,
              two things must happen, we must first understand what traits or
              behaviors seem to be associated with each generation in the
              workforce, and how they perceive effective leadership. By
              examining these expectations, we will be closer to easing the
              transition as one group leaves and the other replaces it as well
              as potentially identifying factors that may help with recruitment
              and retention. The labor force is affected by a number of people
              retiring each year with a direct impact on the economy’s capacity
              to produce goods and services (Ahn & Ettner, 2017). We must be
              careful not to stereotype a particular generation instead, we must
              consider that an individual employee’s preferences may be related
              to maturity, life‐cycle and career stage. This will help us to
              avoid developing generationally specific management policies and
              practices (Macky, Gardner, & Forsyth, 2008){' '}
            </p>

            <p>
              {' '}
              Second, we must take a critical look at how we have been operating
              and why we are not more diverse with regards to gender and
              ethnicity. As we begin to examine our own clinical workforce we
              must take into account individual preferences for leadership
              behavior and acknowledge that this may require a shift in
              leadership attitude, policy, and implementation. (Ahn & Ettner,
              2017) The accepted leadership behavior in most organizations
              outside Orthotics and Prosthetics is transformational leadership,
              a style of leadership where a leader works with subordinates to
              identify needed change, creating a vision to guide the change
              through inspiration, and executing the change in tandem with
              committed members of a group. (Ahn & Ettner, 2017) This model of
              leadership would work well in this profession that maintains a
              need for mentorship in the clinical practice. As we move forward,
              to advance the profession and best care for our diverse patient
              population as well as to promote a more engaged workforce, I would
              suggest that the O& P community focus resources to research
              specifically, the leadership needs of the next generation, and the
              impact of gender and ethnicity has on our workplace and patient
              management.{' '}
            </p>
          </p>
        </div>

        {/* <div>
            <Link to={'/conclusions'}>Next</Link>
          </div>
          <div>
            <Link to={'/comments'}>Tell me what YOU think!</Link>
          </div> */}
      </div>
      <div className="card">
        <ul className="list-group list-group-flush">
          <li className="list-group-item">
            <Link to={'/why'}>Next</Link>
          </li>
          <li className="list-group-item">
            <Link to={'/comments'}>Tell me what YOU think!</Link>
          </li>
        </ul>
      </div>
    </div>
  );
};
export default Theproblem;
